### ISSUE TITLE
Delete plugin/theme not working on WP 4.6

### ISSUE THREAD

**Issue by Marius786** [PressLabs/gitium#113]
Waiting for https://core.trac.wordpress.org/ticket/37587

Hints:

https://github.com/PressLabs/gitium/blob/master/gitium/gitium.php#L230
admin-ajax.php
POST
plugin:woocommerce/woocommerce.php
slug:woocommerce
action:delete-plugin

https://github.com/PressLabs/gitium/blob/master/gitium/gitium.php#L240
admin-ajax.php
POST
slug:content
action:delete-theme

**Comment by Marius786** [comment]
Waiting for https://core.trac.wordpress.org/ticket/37587

**Comment by ocean90** [comment]
You can use the JS events `wp-plugin-delete-success` and `wp-delete-theme-success`, see https://core.trac.wordpress.org/browser/trunk/src/wp-admin/js/updates.js?rev=38199&marks=821&1246#L819.

**Comment by Marius786** [comment]
The plugins have the hooks and the themes are fixed with JS, definitively not the best practice

**Comment by ocean90** [comment]
It's _best practice_ because the update screens are now powered by JS and Ajax.

The missing action for themes wasn't requested until now, it has nothing to do with _best practice_.

**Comment by Marius786** [comment]
Then drop the plugin delete hook, just for consistency. to be used JS and Ajax.
