### ISSUE TITLE
404 error webhook url

### ISSUE THREAD

**Issue by Bananenbaas** [PressLabs/gitium#121]
Hi, 

I've installed your plugin and commits from the webserver to bitbucket are working fine. But the webhook URL gives me a 404 error and I cannot seem to find the error :(

**Comment by krodyrobi** [comment]
Have you tried refreshing the permalinks? If not go to settings>permalinks.

**Comment by Bananenbaas** [comment]
It was a permission error I guess. The wp-content folder was set to 775 instead of 755 :(
