### ISSUE TITLE
Error on pinging git-webhook.php [only sometimes]

### ISSUE THREAD

**Issue by t-ionut** [presslabs/gitium#144]
```PHP User Error:  Failed merge & push: s:567:"error: failed to push some refs to 'git@github.com:pixelgrade/demos.git' hint: Updates were rejected because a pushed branch tip is behind its remote hint: counterpart. Check out this branch and integrate the remote changes hint: (e.g. 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details. To git@github.com:pixelgrade/demos.git =	refs/heads/test:refs/heads/test	[up to date] !	refs/heads/master:refs/heads/master	[rejected] (non-fast-forward) Branch test set up to track remote branch test from origin. Done"; in /www/presslabs/git-webhook.php on line 37 when calling trigger_error(), request: GET /git-webhook.php```

**Comment by cristianuibar** [comment]
Still encountering this issue. Duplicate #183 

```
Sep 19/2019 19:41:14 > PHP User Error: Failed merge & push: s:449:"error: failed to push some refs to 'git@git.presslabs.net:fanatik/fanatik.git'
Sep 19/2019 19:41:14 > hint: Updates were rejected because the tip of your current branch is behind
Sep 19/2019 19:41:14 > hint: its remote counterpart. Integrate the remote changes (e.g.
Sep 19/2019 19:41:14 > hint: 'git pull ...') before pushing again.
Sep 19/2019 19:41:14 > hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Sep 19/2019 19:41:14 > To git@git.presslabs.net:fanatik/fanatik.git
Sep 19/2019 19:41:14 > !\x09HEAD:refs/heads/merge_local\x09[rejected] (non-fast-forward)
Sep 19/2019 19:41:14 > Done"; in /www/presslabs/git-webhook.php on line 37 when calling trigger_error(), request: GET /git-webhook.php, request_id: bb5a7f28912b6d94707d51367bb65605
```

**Comment by DenisFlorin** [comment]
I have not seen this error in the last 3-4 years. I will close it for now.
