### ISSUE TITLE
Disable maintenance even on fails

### ISSUE THREAD

**Issue by cristianuibar** [presslabs/gitium#176]
We need to disable maintenance even if the commit failed for any reason. We have a return for errors but gitium doesn't disable maintenance on fails right now. So it will effectively crash a website if it fails.

**Comment by robertopc** [comment]
This happened in my site.
The fail cause was not have write permissions.
I removed .maintenance file by hands.

**Comment by DenisFlorin** [comment]
This has been fixed.
