### ISSUE TITLE
Unable to configure Gitium

### ISSUE THREAD

**Issue by mike-bunce** [presslabs/gitium#193]
Have tried connecting to remote URL by SSH and HTTPS, neither method are working.
Have tried on https Wordpress install, as well as http. Neither working.
Using Wordpress version: 5.9.2
Please advise

**Comment by DenisFlorin** [comment]
Hi @mike-bunce,

Not sure if you are still interested in our plugin. Let me know if you still need help with the configuration.

Best regards,
