### ISSUE TITLE
Error on `Install new plugin` page

### ISSUE THREAD

**Issue by Marius786** [PressLabs/gitium#21]
Some of your translations need updating. Sit tight for a few more seconds while we update them as well.

Updating translations for Twenty Eleven (es_ES)…

The package could not be installed. No valid plugins were found.

Translation update failed.

![install new plugin error](https://cloud.githubusercontent.com/assets/4104263/3311772/a78a6794-f6c8-11e3-9f00-18ddf2d4de11.png)

**Comment by pdobrescu** [comment]
Needs to be investigated and reproduced.

**Comment by calind** [comment]
@Marius786, @pdobrescu please reopen if this still happens. Right now this issue lives in limbo space.
