### ISSUE TITLE
Merge not working when branches are diverging

### ISSUE THREAD

**Issue by calind** [PressLabs/gitium#30]
If the master branch is one commit ahead and one behind webhook is not working. In the error log is the following message:
`push failed! <pre>error: failed to push some refs to 'ssh://git@git.repo.net/site.git' To prevent you from losing history, non-fast-forward updates were rejected Merge the remote changes (e.g. 'git pull') before pushing again.  See the 'Note about fast-forwards' section of 'git push --help' for details. To ssh://git@git.repo.net/site.git !	refs/heads/master:refs/heads/master	[rejected] (non-fast-forward) Done</pre> in /www/git-webhook.php on line 22 when calling trigger_error(), request: POST /git-webhook.php,`

**Comment by pdobrescu** [comment]
I just reproduced this bug again now on tinybuddha. The only solution was to restart the instance, so it will copy again all the code from the git repo.


Jan 08 09:25:41 bk13-z1 tinybuddha: PHP User Error: push failed! <pre>error: failed to push some refs to 'ssh://git@git.presslabs.net/tinybuddha.git' To prevent you from losing history, non-fast-forward updates were rejected Merge the remote changes (e.g. 'git pull') before pushing again. See the 'Note about fast-forwards' section of 'git push --help' for details. To ssh://git@git.presslabs.net/tinybuddha.git !	refs/heads/master:refs/heads/master	[rejected] (non-fast-forward) Done</pre> in /www/presslabs/git-webhook.php on line 23 when calling trigger_error(), request: POST /./git-webhook.php, request_id: 9ec865efd36d8c4f8986d6aebb12017a

**Comment by calind** [comment]
Closing for now. There is a test for this which passes.
