### ISSUE TITLE
Use the proper path for the Gitium menu icon

### ISSUE THREAD

**Issue by pdobrescu** [PressLabs/gitium#64]
After migrating to Gitium, the console throws this message:

"Mixed Content: The page at 'https://abc.plssl.com/wp-admin/' was loaded over HTTPS, but requested an insecure image 'http://cdn.abc.com/presslabs/lib/gitium/img/gitium.png'. This content should also be served over HTTPS."

Please use the proper path to securely serve the icon

**Comment by calind** [comment]
Fixed. This is presslabs internal issue.
