### ISSUE TITLE
Briefly unavailable for scheduled maintenance. Check back in a minute.

### ISSUE THREAD

**Issue by andresKM** [PressLabs/gitium#69]
After I make a commit in admin area this message appears on the site. The commit isn't made as seen in console and the site works only if I delete .maintenance file in my root.
But at the same time I'm able to work fully with git in console.
Git 1.9.1, latest Gitium, WP 4.1. Whole htdocs/ directory is under www-data user and 644/755 permissions. What could it be?
P.S. Should I change www-data from nologin to bin/bash ?

**Comment by Marius786** [comment]
Hi, can you reproduce this issue all the times? Thanks!

**Comment by andresKM** [comment]
I'm not sure. I think this happens after my work on my repo in console using git...I noticed that after that some files have root owner...I thought it can be a workaroud: 
````
    chown www-data:www-data -R *;
    find . ‐type d ‐exec chmod 755 {} \; 
    find . -type f -exec chmod 644 {} \; 
````
But it should be done as in wp-content on all files and on .git folder.
I saw htdocs/wp-content/plugins/gitium/inc/sss-git must be executable (maybe 755)...
Do I have to make www-data in /bin/sh instead of /bin/nobody ?

**Comment by Marius786** [comment]
I you've right the `sss-git` file must have 755 rights, and the www-data is ok.

**Comment by andresKM** [comment]
What about everything else?

**Comment by Marius786** [comment]
The folder containing the side must be owner by same user which runs WordPress. In your case it's most likely www-data. After issuing:
````
chown www-data:www-data -R *;
find . ‐type d ‐exec chmod 755 {} \; 
find . -type f -exec chmod 644 {} \;
````
you need to make the `ssh-git` script executable.
You do not need to make www-data user use `/bin/sh`.

**Comment by andresKM** [comment]
I checked and this trick works only gitium to work when it commits changes locally on the server or pushes them to a remote repo, but when I try to push from a remote it says "Briefly unavailable for scheduled maintenance. Check back in a minute."
What can I check or smth?

**Comment by andresKM** [comment]
Is it important if I use git in console and I need to type a passphrase when I push? Can It be the reason?

**Comment by selfagency** [comment]
I'm experiencing this same issue. It happens after I hit the commit button in the WordPress backend. It creates a .maintenance file and then nothing else happens—the plugin just stalls. When I delete the .maintenance file and go back into the admin area, nothing's been pulled or pushed. 

![screenshot 2015-06-07 16 43 11](https://cloud.githubusercontent.com/assets/2541728/8026003/63441cc2-0d35-11e5-8199-1fb69d166bb3.png)

**Comment by dirkvebo** [comment]
I also have this issue on two different sites on different servers.

**Comment by Marius786** [comment]
This should be fixed with https://github.com/PressLabs/gitium/pull/106

**Comment by selfagency** [comment]
and it only took a year 😂
