### ISSUE TITLE
Files deleted

### ISSUE THREAD

**Issue by lukeed** [PressLabs/gitium#72]
Activated latest Github version of Gitium. 6 of 14 Plugins deleted. 2 of 3 themes deleted, including active theme.

Will not be using, but reporting issue nonetheless.

**Comment by Marius786** [comment]
Hey, can you, please give us more details about this issue?

**Comment by dennisdornon** [comment]
I just experienced the same issue.  

On initial commit most WordPress files were deleted along with some plugin files, theme files and images. 

WP 4.7.2 

**Plugins**
_Activated_
MainWP Child
Really Simple SSL
Yoast SEO
Gitium
_Deactivated_
VersionPress

Git Version 2.8.1 

Happy to help with any access you need to WordPress or GitHub repository
