### ISSUE TITLE
repo stuck on merge_local branch

### ISSUE THREAD

**Issue by Marius786** [PressLabs/gitium#94]
So we have one:
- test instance: https://marius.plssl.com/wp-admin/options-general.php?page=permalink_finder
- suspect plugin: Permalink Finder Plugin
- front issue: https://app.frontapp.com/inboxes/shared/support/unassigned/81026060
- wrong file: http://git.presslabs.net/?p=1min30.git;a=commit;h=2aa30fa2c110284eb4a733e1c556f18f11bd5b01

Prepare your test instance:
- install and activate the plugin 'Permalink Finder' to the test instance
- put your instance to DEBUG mode from Oxygen
- get your SFTP credentials and be sure you have a SFTP Client App

Until now I investigate the folowing usecase(this usecase is not showing any abnormal behaviour of gitium):
- choose a random post, you can also create a new one
- write and save a wrong url from the test instance, inside of the content
- check the file 'plugins/permalink-finder/.pf_debug_output.txt' on server and see if the file is there and what branch is active ```root@bk4-z3 /containers/.git/marius # git status``` -> ```# On branch master```
- check the file '.pf_debug_output.txt' on gitium page https://marius.plssl.com/wp-admin/admin.php?page=gitium%2Fgitium.php and see if the file is not commited
- check the page https://marius.plssl.com/wp-admin/options-general.php?page=permalink_finder and see if the wronk permalink is detected, if not then press refresh link
- repeat the steps with the wrong permalink
- make a change to some random file via SFTP
- make another change to the same random file choosed before

We must find out what are the real STR! @vtemian can you please tell us more details about this issue?

**Comment by calind** [comment]
This happened today. I have a saved copy of the git repo.

**Comment by calind** [comment]
Possible causes:
* commits at short intervals, so merging cannot catchup
* plugins which continuously generate logging data, so when the webhook is pinged there is already new data to be committed

**Comment by Marius786** [comment]
I confirm the STR (commits at short intervals, so merging cannot catchup):

1. Install approx. 10 themes in the same time; you can do this clicking the scroll button on install ('open in new tab' in a fast way)

**Comment by Marius786** [comment]
related to https://github.com/PressLabs/wp-presslabs/pull/249

**Comment by milero** [comment]
is this finished @Marius786 or ready for review?
