### ISSUE TITLE
Plugin deletes don't get commited

### ISSUE THREAD

**Issue by krodyrobi** [PressLabs/gitium#96]
Expected: Deleting a plugin would cause a commit to be generated and pushed.
Got: nothing, after doing an update to another file or doing a manual commit from the status page they end up in the repo.

**Comment by calind** [comment]
@krodyrobi please give more details

**Comment by krodyrobi** [comment]
@calind  like what could I add more? its a simple delete button that does not get intercepted. It's not a complicated use case 2 steps or more made in sequence.

**Comment by t-ionut** [comment]
Found the problem, it's a GET parameter that changed its value at some point in WordPress on plugin deletion. Fixing the check of the GET param will also fix #95
